version: '3.9'
services:
  ambassador_backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8003:8000
    depends_on:
      - ambassador_db
      - redis
    networks:
      - ambassador
      - users

  ambassador_db:
    image: postgres
    environment:
      POSTGRES_DATABASE: ambassador
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    networks:
      - ambassador

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador

volumes:
  postgres:

networks:
  ambassador:
  users:
    external:
      name: users