version: '3.9'
services:
  users_backed:
    build: .
    container_name: users-ms
    volumes:
      - .:/app
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: postgres
    environment:
      - POSTGRES_DATABASE=users
      - POSTGRES_ROOT_PASSWORD=root
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    networks:
      - users

volumes:
  postgres:

networks:
  users:
    name: users