version: '3.9'
services:
  users_backed:
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - users_db

  users_db:
    image: postgres
    environment:
      - POSTGRES_DATABASE=users
      - POSTGRES_ROOT_PASSWORD=root
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres: